# Generated by Django 3.1.4 on 2021-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, null=True, unique=True)),
                ('correo', models.CharField(max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, null=True, unique=True)),
                ('correo', models.CharField(max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('carnet', models.CharField(max_length=50, null=True, unique=True)),
                ('registro_uni', models.CharField(max_length=50, null=True, unique=True)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('mencion', models.CharField(max_length=50, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, null=True, unique=True)),
                ('correo', models.CharField(max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudInvitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, null=True, unique=True)),
                ('correo', models.CharField(max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('carnet', models.CharField(max_length=50, null=True, unique=True)),
                ('registro_uni', models.CharField(max_length=50, null=True, unique=True)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('mencion', models.CharField(max_length=50, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
