# Generated by Django 3.1.4 on 2021-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinvitado',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
