# Generated by Django 3.1.4 on 2021-06-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20210614_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosestudiante',
            old_name='grupo',
            new_name='grupo_doc',
        ),
    ]
