# Generated by Django 3.1.4 on 2021-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20210614_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='grupo_doc',
            field=models.ForeignKey(null=True, on_delete=models.SET('sin docente'), to='proyecto.datosdocente'),
        ),
    ]
