# Generated by Django 3.1.4 on 2021-06-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20210614_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosestudiante',
            name='grupo_doc',
        ),
    ]
