# Generated by Django 3.1.4 on 2021-06-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_remove_datosestudiante_grupo_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosestudiante',
            name='grupo_doc',
            field=models.ForeignKey(null=True, on_delete=models.SET('sin docente'), to='proyecto.datosdocente'),
        ),
    ]
