# Generated by Django 3.1.4 on 2021-06-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_datosestudiante_grupo_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosestudiante',
            old_name='fecha_solicitud',
            new_name='fecha_inscripcion',
        ),
    ]
