# Generated by Django 3.1.4 on 2021-06-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_auto_20210614_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosdocente',
            name='usuario2',
        ),
    ]
