# Generated by Django 3.1.4 on 2021-06-14 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0016_remove_datosdocente_usuario2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='grupo_doc',
            field=models.ForeignKey(null=True, on_delete=models.SET(''), to='proyecto.datosdocente'),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
