# Generated by Django 3.1.4 on 2021-06-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0020_auto_20210619_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comunicado',
            old_name='title',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='comunicado',
            old_name='text',
            new_name='texto',
        ),
    ]
