# Generated by Django 3.1.4 on 2021-06-20 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0021_auto_20210619_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='tema',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MensajePersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=50, null=True)),
                ('tema', models.CharField(max_length=50, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('autor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
