# Generated by Django 3.1.4 on 2021-06-20 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0024_mensajeestdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_conversacion', models.CharField(max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mensajeestdoc',
            name='lado_a',
        ),
        migrations.RemoveField(
            model_name='mensajeestdoc',
            name='lado_b',
        ),
        migrations.RemoveField(
            model_name='mensajeestdoc',
            name='texto_a',
        ),
        migrations.RemoveField(
            model_name='mensajeestdoc',
            name='texto_b',
        ),
        migrations.AddField(
            model_name='mensajeestdoc',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensajeestdoc',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajeestdoc',
            name='conversacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.conversacion'),
        ),
    ]
