# Generated by Django 3.1.4 on 2021-06-20 22:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0025_auto_20210620_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensajeEstDoc',
            new_name='Mensaje',
        ),
    ]
