# Generated by Django 3.1.4 on 2021-06-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0027_auto_20210620_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='para',
            old_name='nombre_estinatario',
            new_name='nombre_destinatario',
        ),
    ]
