# Generated by Django 3.1.4 on 2021-06-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0028_auto_20210620_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='conversacion',
            new_name='para',
        ),
    ]
