# Generated by Django 3.1.4 on 2021-06-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0029_auto_20210620_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversacion',
        ),
        migrations.DeleteModel(
            name='MensajePersonal',
        ),
    ]
