# Generated by Django 3.1.4 on 2021-06-22 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0030_auto_20210622_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='para',
            name='nombre_destinatario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
