# Generated by Django 3.1.4 on 2021-06-23 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0032_mensajeusuario_sala'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensajeUsuario',
            new_name='MensajeSala',
        ),
    ]
