# Generated by Django 3.1.4 on 2021-06-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0034_auto_20210628_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosestudiante',
            name='nombre_sala_docente',
        ),
        migrations.RemoveField(
            model_name='datosestudiante',
            name='nombre_sala_tutor',
        ),
    ]
