# Generated by Django 3.1.4 on 2021-06-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0035_auto_20210628_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='para',
            name='nombre_destinatario',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.DeleteModel(
            name='Para',
        ),
    ]
