# Generated by Django 3.1.4 on 2021-06-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0037_reglamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglamento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='reglamentos/'),
        ),
    ]
