# Generated by Django 3.1.4 on 2021-06-29 23:01

from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0038_auto_20210629_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglamento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='reglamentos/', validators=[proyecto.models.validate_file_extension]),
        ),
    ]
