# Generated by Django 3.1.4 on 2021-06-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0039_auto_20210629_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='datostutor',
            name='material_docente',
            field=models.FileField(blank=True, null=True, upload_to='material_docente/'),
        ),
    ]
