# Generated by Django 3.1.4 on 2021-06-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0040_datostutor_material_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datostutor',
            name='nombre_sala_estudiante',
        ),
    ]
