# Generated by Django 3.1.4 on 2021-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0041_remove_datostutor_nombre_sala_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosdocente',
            name='nombre_sala_estudiante',
        ),
        migrations.RemoveField(
            model_name='datostutor',
            name='material_docente',
        ),
        migrations.AddField(
            model_name='datosdocente',
            name='material_docente',
            field=models.FileField(blank=True, null=True, upload_to='material_docente/'),
        ),
    ]
