# Generated by Django 3.1.4 on 2021-06-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0044_auto_20210630_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdocente',
            name='propietario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosdocente'),
        ),
    ]
