# Generated by Django 3.1.4 on 2021-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0047_auto_20210701_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdocente',
            name='material_docente',
            field=models.FileField(null=True, upload_to='material_docente/'),
        ),
    ]
