# Generated by Django 3.1.4 on 2021-07-01 20:56

from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0052_auto_20210701_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglamento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media/reglamentos/', validators=[proyecto.models.validate_file_extension]),
        ),
    ]
