# Generated by Django 3.1.4 on 2021-07-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0056_materialestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialestudiante',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
