# Generated by Django 3.1.4 on 2021-07-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0059_auto_20210708_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalaCorreccion',
            new_name='SalaRevisar',
        ),
    ]
