# Generated by Django 3.1.4 on 2021-07-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0062_auto_20210708_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialestudiante',
            old_name='est_rev',
            new_name='estudiante_rev',
        ),
    ]
