# Generated by Django 3.1.4 on 2021-07-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0065_mensajerevisar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialestudiante',
            old_name='sala_revisar',
            new_name='sala',
        ),
    ]
