# Generated by Django 3.1.4 on 2021-07-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0066_auto_20210708_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarevisar',
            name='material_estudiante',
            field=models.FileField(null=True, upload_to='material_estudiante/'),
        ),
    ]
