# Generated by Django 3.1.4 on 2021-07-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0069_mensajerevisar_docente_rev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajerevisar',
            old_name='docente_rev',
            new_name='usuario',
        ),
    ]
