# Generated by Django 3.1.4 on 2021-07-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0072_registroperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroperfil',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
