# Generated by Django 3.1.4 on 2021-07-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0073_auto_20210723_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroperfil',
            name='cronograma',
        ),
    ]
