# Generated by Django 3.1.4 on 2021-07-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0074_remove_registroperfil_cronograma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroperfil',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
