# Generated by Django 3.1.4 on 2021-07-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0075_auto_20210723_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroperfil',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
