# Generated by Django 3.1.4 on 2021-07-24 19:42

from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0077_auto_20210723_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reglamentos/', validators=[proyecto.models.validate_file_extension])),
            ],
        ),
    ]
