# Generated by Django 3.1.4 on 2021-07-24 19:47

from django.db import migrations, models
import proyecto.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0078_formularios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularios',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='formularios/', validators=[proyecto.models.validate_file_extension]),
        ),
    ]
