# Generated by Django 3.1.4 on 2021-07-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0082_auto_20210726_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocronograma',
            name='semana',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
