# Generated by Django 3.1.4 on 2021-07-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0085_auto_20210726_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocronograma',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrocronograma',
            name='semana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
