# Generated by Django 3.1.4 on 2021-07-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0087_auto_20210726_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocronograma',
            name='semana',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
