# Generated by Django 3.1.4 on 2021-07-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0089_auto_20210726_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosestudiante',
            name='cronograma',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
