# Generated by Django 3.1.4 on 2021-07-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0090_datosestudiante_cronograma'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroCronograma',
            new_name='ActividadesCronograma',
        ),
    ]
