# Generated by Django 3.1.4 on 2021-07-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0093_salarevisarproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEstudianteProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('material_estudiante', models.FileField(null=True, upload_to='material_estudiante/')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.salarevisar')),
            ],
        ),
    ]
