# Generated by Django 3.1.4 on 2021-07-31 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0095_auto_20210731_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialestudianteproyecto',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.salarevisarproyecto'),
        ),
    ]
