# Generated by Django 3.1.4 on 2021-08-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0099_proyectodegrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectodegrado',
            name='calificacion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
