# Generated by Django 3.2.6 on 2021-08-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0103_datosestudiante_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudinvitado',
            name='extension',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
