# Generated by Django 3.2.6 on 2021-08-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0104_solicitudinvitado_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosestudiante',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
