# Generated by Django 3.2.6 on 2021-08-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0105_datosestudiante_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile1.png', null=True, upload_to=''),
        ),
    ]
