# Generated by Django 3.2.6 on 2021-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0106_alter_datosestudiante_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='extension',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
