# Generated by Django 3.2.6 on 2021-08-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0109_auto_20210827_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='images/profile1.png', null=True, upload_to='images/'),
        ),
    ]
