# Generated by Django 3.2.6 on 2021-08-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0110_alter_datosestudiante_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='imagen_perfil',
            field=models.ImageField(default='imagenes/profile1.png', null=True, upload_to=''),
        ),
    ]
