# Generated by Django 3.2.6 on 2021-08-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0114_auto_20210828_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='vb_perfil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='vb_proyecto',
            field=models.BooleanField(default=False),
        ),
    ]
