# Generated by Django 3.2.6 on 2021-08-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0116_auto_20210828_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosestudiante',
            name='aceptar_tutoria',
            field=models.BooleanField(default=False),
        ),
    ]
