# Generated by Django 3.2.6 on 2021-08-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0118_rename_aceptar_tutoria_datosestudiante_tutor_acepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200, null=True)),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
