# Generated by Django 3.2.6 on 2021-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0120_auto_20210831_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto')], max_length=200, null=True),
        ),
    ]
