# Generated by Django 3.2.6 on 2021-09-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0122_alter_busquedaproyecto_perfil_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroperfil',
            name='perfil',
            field=models.FileField(null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto')], max_length=200, null=True),
        ),
    ]
