# Generated by Django 3.2.6 on 2021-09-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0123_auto_20210902_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectodegrado',
            name='archivo',
            field=models.FileField(null=True, upload_to='proyectos/'),
        ),
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('perfil', 'Perfil')], max_length=200, null=True),
        ),
    ]
