# Generated by Django 3.2.6 on 2021-09-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0124_auto_20210902_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectodegrado',
            name='nota_cumplimiento_cronograma',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectodegrado',
            name='nota_expos_seminarios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectodegrado',
            name='nota_informes_trabajo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectodegrado',
            name='nota_tiempo_elaboracion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
