# Generated by Django 3.2.6 on 2021-09-03 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0125_auto_20210903_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auspicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=200, null=True)),
                ('supervisor', models.CharField(default='', max_length=200, null=True)),
                ('cargo', models.CharField(default='', max_length=200, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante')),
            ],
        ),
    ]
