# Generated by Django 3.2.6 on 2021-09-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0126_auspicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdocente',
            name='firma',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='datosestudiante',
            name='firma',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='datostutor',
            name='firma',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
