# Generated by Django 3.2.6 on 2021-09-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0129_auto_20210904_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmas',
            name='firma',
            field=models.ImageField(default='img-firmas/firma_default.jpg', null=True, upload_to='imagenes/'),
        ),
    ]
