# Generated by Django 3.2.6 on 2021-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0132_auto_20210904_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('perfil', 'Perfil')], max_length=200, null=True),
        ),
    ]
