# Generated by Django 3.2.6 on 2021-09-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0137_alter_busquedaproyecto_perfil_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto')], max_length=200, null=True),
        ),
    ]
