# Generated by Django 3.2.6 on 2021-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0139_auto_20210909_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarevisarproyecto',
            name='material_corregido_docente',
            field=models.FileField(blank=True, null=True, upload_to='material_estudiante_perfil/'),
        ),
        migrations.AddField(
            model_name='salarevisarproyecto',
            name='material_corregido_tutor',
            field=models.FileField(blank=True, null=True, upload_to='material_estudiante_perfil/'),
        ),
        migrations.AlterField(
            model_name='salarevisar',
            name='material_corregido_docente',
            field=models.FileField(blank=True, null=True, upload_to='material_estudiante_perfil/'),
        ),
        migrations.AlterField(
            model_name='salarevisar',
            name='material_corregido_tutor',
            field=models.FileField(blank=True, null=True, upload_to='material_estudiante_perfil/'),
        ),
    ]
