# Generated by Django 3.2.6 on 2021-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0140_auto_20210909_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosdocente',
            name='firma',
            field=models.ImageField(default='firmas/firma_default.jpg', null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='firma_formulario1_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentos',
            name='firma_formulario2_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentos',
            name='firma_formulario4_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('perfil', 'Perfil')], max_length=200, null=True),
        ),
    ]
