# Generated by Django 3.2.6 on 2021-09-11 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0144_auto_20210910_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEstudianteTitulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('carnet', models.CharField(max_length=50, null=True, unique=True)),
                ('extension', models.CharField(max_length=50, null=True)),
                ('registro_uni', models.CharField(max_length=50, null=True, unique=True)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('mencion', models.CharField(max_length=50, null=True)),
                ('tutor', models.CharField(max_length=100, null=True)),
                ('docente', models.CharField(max_length=100, null=True)),
                ('imagen_perfil', models.ImageField(default='imagenes/profile1.png', null=True, upload_to='imagenes/')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
