# Generated by Django 3.2.6 on 2021-09-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0145_datosestudiantetitulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosestudiantetitulado',
            name='usuario',
        ),
    ]
