# Generated by Django 3.2.6 on 2021-09-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0147_auto_20210911_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdocente',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
