# Generated by Django 3.2.6 on 2021-09-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0148_materialdocente_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglamento',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
