# Generated by Django 3.2.6 on 2021-09-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0152_auto_20210912_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistareglamento',
            name='reglamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.reglamento'),
        ),
    ]
