# Generated by Django 3.2.6 on 2021-09-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0153_alter_vistareglamento_reglamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglamento',
            name='visto',
        ),
    ]
