# Generated by Django 3.2.6 on 2021-09-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0154_remove_reglamento_visto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistareglamento',
            name='reglamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.reglamento'),
        ),
    ]
