# Generated by Django 3.2.6 on 2021-09-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0155_alter_vistareglamento_reglamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('perfil', 'Perfil')], max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='vistareglamento',
            name='reglamento',
        ),
        migrations.AddField(
            model_name='vistareglamento',
            name='reglamento',
            field=models.ManyToManyField(blank=True, null=True, to='proyecto.Reglamento'),
        ),
        migrations.AlterField(
            model_name='vistareglamento',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante'),
        ),
    ]
