# Generated by Django 3.2.6 on 2021-09-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0156_auto_20210912_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistareglamento',
            name='reglamento',
        ),
        migrations.AddField(
            model_name='vistareglamento',
            name='reglamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.reglamento'),
        ),
        migrations.AlterField(
            model_name='vistareglamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante'),
        ),
    ]
