# Generated by Django 3.2.6 on 2021-09-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0161_auto_20210912_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajedocenterevisar',
            name='visto_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajedocenterevisar',
            name='visto_estudiante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto')], max_length=200, null=True),
        ),
    ]
