# Generated by Django 3.2.6 on 2021-09-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0162_auto_20210913_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajetutorrevisar',
            name='visto_estudiante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajetutorrevisar',
            name='visto_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('perfil', 'Perfil')], max_length=200, null=True),
        ),
    ]
