# Generated by Django 3.2.6 on 2021-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0164_alter_busquedaproyecto_perfil_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajedocenterevisarproyecto',
            name='visto_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajedocenterevisarproyecto',
            name='visto_estudiante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajetutorrevisarproyecto',
            name='visto_estudiante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajetutorrevisarproyecto',
            name='visto_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
