# Generated by Django 3.2.6 on 2021-10-26 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0166_auto_20211014_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DatosTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('celular', models.CharField(max_length=50, null=True)),
                ('firma', models.ImageField(default='firmas/firma_default.jpg', null=True, upload_to='firmas/')),
                ('imagen_perfil', models.ImageField(default='imagenes/profile1.png', null=True, upload_to='imagenes/')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
