# Generated by Django 3.2.6 on 2021-10-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0168_auto_20211028_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosestudiante',
            name='tribunales',
            field=models.ManyToManyField(to='proyecto.DatosTribunal'),
        ),
        migrations.AlterField(
            model_name='busquedaproyecto',
            name='perfil_proyecto',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto')], max_length=200, null=True),
        ),
    ]
