# Generated by Django 3.2.6 on 2021-11-08 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0169_auto_20211029_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaRevisarTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=50, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('material_estudiante', models.FileField(null=True, upload_to='material_estudiante_proyecto/')),
                ('visto_bueno', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('estudiante_rev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante')),
                ('tribunal_rev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datostribunal')),
            ],
        ),
    ]
