# Generated by Django 3.2.6 on 2021-11-15 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0171_mensajetribunalrevisar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProyectoTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(null=True, upload_to='proyectos/')),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante')),
            ],
        ),
    ]
