# Generated by Django 3.2.6 on 2022-01-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0177_alter_solicitudinvitado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudinvitado',
            name='usuario',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
