# Generated by Django 4.0.2 on 2022-02-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0181_alter_solicitudinvitado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajedocenterevisarproyecto',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='mensajedocenterevisarproyecto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='mensajetribunalrevisar',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='mensajetribunalrevisar',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='mensajetutorrevisar',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='mensajetutorrevisar',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='mensajetutorrevisarproyecto',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='mensajetutorrevisarproyecto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='salarevisar',
            name='docente_rev',
        ),
        migrations.RemoveField(
            model_name='salarevisar',
            name='estudiante_rev',
        ),
        migrations.RemoveField(
            model_name='salarevisar',
            name='tutor_rev',
        ),
        migrations.RemoveField(
            model_name='salarevisarproyecto',
            name='docente_rev',
        ),
        migrations.RemoveField(
            model_name='salarevisarproyecto',
            name='estudiante_rev',
        ),
        migrations.RemoveField(
            model_name='salarevisarproyecto',
            name='tutor_rev',
        ),
        migrations.RemoveField(
            model_name='salarevisartribunal',
            name='estudiante_rev',
        ),
        migrations.RemoveField(
            model_name='salarevisartribunal',
            name='tribunal_rev',
        ),
        migrations.DeleteModel(
            name='MensajeDocenteRevisar',
        ),
        migrations.DeleteModel(
            name='MensajeDocenteRevisarProyecto',
        ),
        migrations.DeleteModel(
            name='MensajeTribunalRevisar',
        ),
        migrations.DeleteModel(
            name='MensajeTutorRevisar',
        ),
        migrations.DeleteModel(
            name='MensajeTutorRevisarProyecto',
        ),
        migrations.DeleteModel(
            name='SalaRevisar',
        ),
        migrations.DeleteModel(
            name='SalaRevisarProyecto',
        ),
        migrations.DeleteModel(
            name='SalaRevisarTribunal',
        ),
    ]
