# Generated by Django 4.0.2 on 2022-02-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0183_grupoestudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoestudiante',
            name='integrante',
        ),
        migrations.AddField(
            model_name='grupoestudiante',
            name='integrantes',
            field=models.ManyToManyField(to='proyecto.DatosEstudiante'),
        ),
    ]
