# Generated by Django 4.0.2 on 2022-02-08 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0184_remove_grupoestudiante_integrante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoestudiante',
            name='integrantes',
        ),
        migrations.AddField(
            model_name='datosestudiante',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.grupoestudiante'),
        ),
        migrations.AddField(
            model_name='grupoestudiante',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grupoestudiante',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.registroperfil'),
        ),
    ]
