# Generated by Django 4.0.2 on 2022-02-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0188_remove_datosestudiante_vb_perfil_docente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunal_2_estudiante',
            name='tribunal_2',
        ),
        migrations.RemoveField(
            model_name='tribunal_2_estudiante',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Tribunal_1_Estudiante',
        ),
        migrations.DeleteModel(
            name='Tribunal_2_Estudiante',
        ),
    ]
