# Generated by Django 4.0.2 on 2022-02-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0189_remove_tribunal_2_estudiante_tribunal_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoestudiante',
            name='perfil',
        ),
        migrations.AddField(
            model_name='datosestudiante',
            name='modalidad',
            field=models.CharField(choices=[('individual', 'Individual'), ('multiple', 'Multiple')], default='individual', max_length=200, null=True),
        ),
    ]
