# Generated by Django 4.0.2 on 2022-02-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0192_alter_datosestudiante_tribunales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrupoEstudiante',
            new_name='Equipo',
        ),
        migrations.RenameField(
            model_name='datosestudiante',
            old_name='grupo_est',
            new_name='equipo',
        ),
    ]
