# Generated by Django 4.0.2 on 2022-02-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0193_rename_grupoestudiante_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('multiple', 'Multiple')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SolicitudMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, default='Solicitud de Modalidad Multiple', max_length=50, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosdocente')),
            ],
        ),
    ]
