# Generated by Django 4.0.2 on 2022-02-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0194_alter_datosestudiante_modalidad_solicitudmultiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmultiple',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosdocente'),
        ),
        migrations.AlterField(
            model_name='solicitudmultiple',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante'),
        ),
    ]
