# Generated by Django 4.0.2 on 2022-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0195_solicitudmultiple_docente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmultiple',
            name='visto_bueno',
            field=models.BooleanField(default=False),
        ),
    ]
