# Generated by Django 4.0.2 on 2022-02-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0197_rename_visto_bueno_solicitudmultiple_aprobar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudMultiple',
        ),
    ]
