# Generated by Django 4.0.2 on 2022-02-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0199_alter_equipo_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('valor', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='datosestudiante',
            name='actividad',
            field=models.ManyToManyField(null=True, to='proyecto.Actividad'),
        ),
    ]
