# Generated by Django 4.0.2 on 2022-02-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0200_actividad_datosestudiante_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='actividad',
            field=models.ManyToManyField(to='proyecto.Actividad'),
        ),
    ]
