# Generated by Django 4.0.2 on 2022-02-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_initial'),
        ('proyecto', '0201_alter_datosestudiante_actividad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='actividad',
            field=models.ManyToManyField(blank=True, to='actividades.Actividad'),
        ),
    ]
