# Generated by Django 4.0.2 on 2022-02-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0202_delete_actividad_alter_datosestudiante_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.datostutor'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tutor_acepto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('multiple', 'Múltiple')], max_length=200, null=True),
        ),
    ]
