# Generated by Django 4.0.2 on 2022-02-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0203_equipo_tutor_equipo_tutor_acepto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.datosdocente'),
        ),
    ]
