# Generated by Django 4.0.2 on 2022-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0204_equipo_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tribunales',
            field=models.ManyToManyField(blank=True, to='proyecto.DatosTribunal'),
        ),
    ]
