# Generated by Django 4.0.2 on 2022-02-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0205_equipo_tribunales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectodegrado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='proyectodegrado',
            name='equipo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.equipo'),
        ),
    ]
