# Generated by Django 4.0.2 on 2022-02-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0206_remove_proyectodegrado_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadescronograma',
            name='usuario',
        ),
        migrations.AddField(
            model_name='actividadescronograma',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.equipo'),
        ),
    ]
