# Generated by Django 4.0.2 on 2022-02-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0210_remove_registrocronograma_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosestudiante',
            name='tribunales',
        ),
        migrations.RemoveField(
            model_name='datosestudiante',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='datosestudiante',
            name='tutor_acepto',
        ),
    ]
