# Generated by Django 4.0.2 on 2022-02-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0212_equipo_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosestudiante',
            name='solicitud_tribunal_docente',
        ),
        migrations.AddField(
            model_name='equipo',
            name='solicitud_tribunal_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
