# Generated by Django 4.0.2 on 2022-02-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0214_remove_registroproyectotribunal_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroproyectotribunal',
            name='nota_final',
        ),
        migrations.CreateModel(
            name='NotaTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.equipo')),
                ('tribunal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datostribunal')),
            ],
        ),
    ]
