# Generated by Django 4.0.2 on 2022-03-04 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0217_equipo_fecha_conclusion_alter_equipo_nota_final'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusquedaProyecto',
        ),
    ]
