# Generated by Django 4.0.2 on 2022-03-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0219_datosestudiante_imagen_perfil_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudiante',
            name='imagen_perfil_web',
            field=models.URLField(default='https://p16-va-default.akamaized.net/img/musically-maliva-obj/1665282759496710~c5_720x720.jpeg', null=True),
        ),
    ]
