# Generated by Django 4.0.2 on 2022-03-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0220_alter_datosestudiante_imagen_perfil_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosestudiante',
            name='modalidad_aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
