# Generated by Django 4.0.2 on 2022-03-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0221_datosestudiante_modalidad_aprobada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosestudiante',
            old_name='modalidad_aprobada',
            new_name='is_modalidad_aprobada',
        ),
    ]
