# Generated by Django 4.0.2 on 2022-04-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0222_rename_modalidad_aprobada_datosestudiante_is_modalidad_aprobada'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectodegrado',
            name='bibliografia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proyectodegrado',
            name='indice',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registroperfil',
            name='bibliografia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registroperfil',
            name='indice',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registroproyectotribunal',
            name='bibliografia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='registroproyectotribunal',
            name='indice',
            field=models.TextField(null=True),
        ),
    ]
