# Generated by Django 4.0.2 on 2022-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0223_proyectodegrado_bibliografia_proyectodegrado_indice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=2, null=True),
        ),
    ]
