# Generated by Django 4.0.2 on 2022-04-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0224_alter_equipo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajesala',
            name='is_visto',
            field=models.BooleanField(default=False),
        ),
    ]
