# Generated by Django 4.0.2 on 2022-05-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0225_mensajesala_is_visto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadescronograma',
            name='semana_final',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actividadescronograma',
            name='semana_inicial',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='proyectodegrado',
            name='nota_cumplimiento_cronograma',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='proyectodegrado',
            name='nota_expos_seminarios',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='proyectodegrado',
            name='nota_tiempo_elaboracion',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
    ]
