# Generated by Django 4.0.2 on 2022-06-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0226_alter_actividadescronograma_semana_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='is_concluido',
            field=models.BooleanField(default=False),
        ),
    ]
