# Generated by Django 4.0.2 on 2022-06-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0227_equipo_is_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='datostribunal',
            name='menciones',
            field=models.ManyToManyField(blank=True, to='proyecto.Mencion'),
        ),
        migrations.AlterField(
            model_name='datosadministrador',
            name='correo',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datosdirector',
            name='correo',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datosdocente',
            name='correo',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datosestudiante',
            name='correo',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datosestudiantetitulado',
            name='correo',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datostribunal',
            name='correo',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datostutor',
            name='correo',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudinvitado',
            name='correo',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
