# Generated by Django 4.0.2 on 2022-06-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0229_datosestudiante_is_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosestudiante',
            name='nivel_ie',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
