# Generated by Django 4.0.2 on 2022-08-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0236_alter_datosestudiante_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progreso',
        ),
    ]
