# Generated by Django 4.0.2 on 2022-05-21 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0226_alter_actividadescronograma_semana_final_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaDocumentoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_bueno', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto'), ('tribunal', 'Proyecto Tribunal')], max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.equipo')),
                ('grupo_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaRevisarDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('archivo_corregir', models.FileField(null=True, upload_to='material_estudiante_perfil/')),
                ('archivo_corregir_web', models.URLField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante')),
                ('sala_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revisar_documentos.saladocumentodoc')),
            ],
        ),
        migrations.CreateModel(
            name='NotaSalaRevisarDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True)),
                ('nota_max', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True)),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revisar_documentos.salarevisardoc')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeRevisarDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('visto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revisar_documentos.salarevisardoc')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
