# Generated by Django 4.0.2 on 2022-05-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revisar_documentos', '0003_remove_salarevisardocpredeterminado_sala_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarevisardocpredeterminado',
            name='sala_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revisar_documentos.saladocumentodoc'),
        ),
    ]
