# Generated by Django 4.0.2 on 2022-05-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar_documentos', '0004_salarevisardocpredeterminado_sala_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisarDocPredeterminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=2, null=True)),
                ('asunto', models.CharField(max_length=200, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SalaRevisarDocPredeterminado',
        ),
    ]
