# Generated by Django 4.0.2 on 2022-05-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar_documentos', '0005_revisardocpredeterminado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revisardocpredeterminado',
            options={'ordering': ['-orden']},
        ),
        migrations.AddField(
            model_name='revisardocpredeterminado',
            name='tipo',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Borrador de Proyecto'), ('tribunal', 'Proyecto Final Tribunal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='revisardocpredeterminado',
            name='orden',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salarevisardoc',
            name='archivo_corregir',
            field=models.FileField(blank=True, null=True, upload_to='material_estudiante_perfil/'),
        ),
    ]
