# Generated by Django 4.0.2 on 2022-05-25 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revisar_documentos', '0006_alter_revisardocpredeterminado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saladocumentodoc',
            name='is_predeterminado',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RevisarDocPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(null=True)),
                ('asunto', models.CharField(max_length=200, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Borrador de Proyecto'), ('tribunal', 'Proyecto Final Tribunal')], max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-orden'],
            },
        ),
    ]
