# Generated by Django 4.0.2 on 2022-05-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar_documentos', '0007_saladocumentodoc_is_predeterminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarevisardoc',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='salarevisardoc',
            name='nota_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
    ]
