# Generated by Django 4.0.2 on 2022-05-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar_documentos', '0010_revisardocpredeterminado_nota_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarevisardoc',
            name='is_calificado',
            field=models.BooleanField(default=False),
        ),
    ]
