# Generated by Django 4.0.2 on 2022-08-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revisar_documentos', '0012_remove_saladocumentodoc_is_predeterminado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saladocumentodoc',
            name='updated',
        ),
    ]
