# Generated by Django 4.0.2 on 2022-08-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar_documentos', '0013_remove_saladocumentodoc_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='saladocumentodoc',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
