# Generated by Django 4.0.2 on 2022-02-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='actividad',
            name='orden',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='valor',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
