# Generated by Django 4.0.2 on 2022-02-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0190_remove_grupoestudiante_perfil_and_more'),
        ('actividades', '0002_alter_actividad_options_actividad_orden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-orden']},
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='hecho',
        ),
        migrations.CreateModel(
            name='RealizarActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hecho', models.BooleanField(default=False)),
                ('propietario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante')),
            ],
        ),
    ]
