# Generated by Django 4.0.2 on 2022-02-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_realizaractividad_actividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realizaractividad',
            old_name='propietario',
            new_name='estudiante',
        ),
    ]
