# Generated by Django 4.0.2 on 2022-02-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0192_alter_datosestudiante_tribunales'),
        ('actividades', '0005_rename_propietario_realizaractividad_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizaractividad',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante'),
        ),
    ]
