# Generated by Django 4.0.2 on 2022-02-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_alter_realizaractividad_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={},
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='fecha_inscripcion',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='orden',
        ),
        migrations.DeleteModel(
            name='RealizarActividad',
        ),
    ]
