# Generated by Django 4.0.2 on 2022-02-13 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_alter_actividad_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
