# Generated by Django 4.0.2 on 2022-02-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_alter_actividad_options_actividad_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['orden']},
        ),
    ]
