# Generated by Django 4.0.2 on 2022-04-05 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0223_proyectodegrado_bibliografia_proyectodegrado_indice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0013_alter_actividad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('cantidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('actividades', models.ManyToManyField(blank=True, to='actividades.Actividad')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.equipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
