# Generated by Django 4.0.2 on 2022-04-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_avisoactividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisoactividad',
            name='cantidad',
        ),
    ]
