# Generated by Django 4.0.2 on 2022-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0016_actividadhistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nombre_humano',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
