# Generated by Django 4.0.2 on 2022-06-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0017_actividad_nombre_humano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nombre_humano',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
