# Generated by Django 4.0.2 on 2022-03-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosinscritos',
            name='tutor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proyectosinscritos',
            name='estado',
            field=models.CharField(choices=[('concluido', 'Concluido'), ('en proceso', 'En proceso')], default='en proceso', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proyectosinscritos',
            name='fecha_concluida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectosinscritos',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectosinscritos',
            name='tipo',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto')], default='proyecto', max_length=200, null=True),
        ),
    ]
