# Generated by Django 4.0.2 on 2022-03-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busquedas', '0003_proyectosexcel_proyectosinscritos_docente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosexcel',
            name='mencion',
            field=models.CharField(choices=[('telecomunicacion', 'Telecomunicación'), ('control', 'Control'), ('sistemas', 'Sistemas de Computación')], default='proyecto', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyectosexcel',
            name='sigla_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyectosexcel',
            name='tesistas',
            field=models.SmallIntegerField(null=True),
        ),
    ]
