# Generated by Django 4.0.2 on 2022-04-18 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0225_mensajesala_is_visto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(null=True, upload_to='documentos/')),
                ('tipo', models.CharField(blank=True, choices=[('carta_aceptacion', 'Carta de Aceptación'), ('carta_conclusion', 'Carta de Conclusión'), ('formulario_aprobacion', 'Formulario Aprobación de Perfil'), ('formulario_solicitud_tribunal', 'Formulario de Solicitud de Nombramiento de Tribunal'), ('formulario_registro_seguimiento', 'Formulario de Registro y Seguimiento'), ('formulario_materia', 'Formulario Materia: Proyecto')], max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.equipo')),
            ],
        ),
    ]
