# Generated by Django 4.0.2 on 2022-08-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('carta_aceptacion', 'Carta de Aceptación'), ('carta_conclusion', 'Carta de Conclusión'), ('formulario_aprobacion', 'Formulario Aprobación de Perfil'), ('formulario_solicitud_tribunal', 'Formulario de Solicitud de Nombramiento de Tribunal'), ('formulario_registro_seguimiento', 'Formulario de Registro y Seguimiento'), ('formulario_materia', 'Formulario Materia: Proyecto'), ('planilla_avance', 'Planilla de Avance')], max_length=200, null=True),
        ),
    ]
