# Generated by Django 4.0.2 on 2022-05-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0226_alter_actividadescronograma_semana_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('equipo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.equipo')),
            ],
        ),
    ]
