# Generated by Django 4.0.2 on 2022-02-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0198_delete_solicitudmultiple'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, default='Solicitud de Modalidad Múltiple', max_length=50, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('visto', models.BooleanField(default=False)),
                ('aprobar', models.BooleanField(default=False)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosdocente')),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante')),
            ],
        ),
        migrations.CreateModel(
            name='RechazoSolicitudMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, default='Solicitud Rechazada', max_length=50, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('visto', models.BooleanField(default=False)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosdocente')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante')),
            ],
        ),
    ]
