# Generated by Django 4.0.2 on 2022-02-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0198_delete_solicitudmultiple'),
        ('modalidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RechazoSolicitudMultiple',
            new_name='RechazoSolicitud',
        ),
        migrations.RenameModel(
            old_name='SolicitudMultiple',
            new_name='Solicitud',
        ),
    ]
