# Generated by Django 4.0.2 on 2022-02-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidad', '0002_rename_rechazosolicitudmultiple_rechazosolicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechazosolicitud',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
