# Generated by Django 4.0.2 on 2022-02-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0198_delete_solicitudmultiple'),
        ('modalidad', '0003_rechazosolicitud_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RechazoSolicitud',
            new_name='RechazarSolicitud',
        ),
    ]
