# Generated by Django 4.0.2 on 2022-02-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidad', '0007_remove_solicitudintegrante_estudiante_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudintegrante',
            name='correo_invitado',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
