# Generated by Django 4.0.2 on 2022-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidad', '0008_solicitudintegrante_correo_invitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudintegrante',
            name='correo_invitado',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
