# Generated by Django 4.0.2 on 2022-02-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidad', '0010_remove_solicitudintegrante_estudiante_interesado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudintegrante',
            name='aprobar',
        ),
        migrations.RemoveField(
            model_name='solicitudintegrante',
            name='rechazar',
        ),
        migrations.AddField(
            model_name='solicitudintegrante',
            name='estado',
            field=models.CharField(choices=[('aprobar', 'Aprobar'), ('rechazar', 'Rechazar')], max_length=50, null=True),
        ),
    ]
