# Generated by Django 4.0.2 on 2022-02-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidad', '0011_remove_solicitudintegrante_aprobar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudintegrante',
            name='estado',
            field=models.CharField(blank=True, choices=[('aprobar', 'Aprobar'), ('rechazar', 'Rechazar')], max_length=50, null=True),
        ),
    ]
