# Generated by Django 3.2.6 on 2021-11-19 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensaje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajepar',
            name='de',
        ),
        migrations.RemoveField(
            model_name='mensajepar',
            name='para',
        ),
        migrations.CreateModel(
            name='CanalPar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='de', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='para', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mensajepar',
            name='canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mensaje.canalpar'),
        ),
    ]
