# Generated by Django 3.2.6 on 2021-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensaje', '0002_auto_20211119_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalpar',
            name='tipo',
            field=models.CharField(choices=[('OBSERVAR', 'OBSERVAR'), ('MENSAJE', 'MENSAJE')], max_length=200, null=True),
        ),
    ]
