# Generated by Django 4.0.2 on 2022-04-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensaje', '0035_alter_canalpar_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalpar',
            name='tipo',
        ),
    ]
