# Generated by Django 3.2.6 on 2021-11-23 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('proyecto', '0174_alter_busquedaproyecto_perfil_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revisar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarevisarapp',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='salarevisarapp',
            name='grupo_revisor',
        ),
        migrations.RemoveField(
            model_name='salarevisarapp',
            name='revisor',
        ),
        migrations.RemoveField(
            model_name='salarevisarapp',
            name='tipo',
        ),
        migrations.CreateModel(
            name='SalaDocumentoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_bueno', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto'), ('tribunal', 'Tribunal')], max_length=50, null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.datosestudiante')),
                ('grupo_revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salarevisarapp',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revisar.saladocumentoapp'),
        ),
    ]
