# Generated by Django 3.2.6 on 2021-11-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revisar', '0002_auto_20211123_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarevisarapp',
            name='documento',
        ),
        migrations.AddField(
            model_name='salarevisarapp',
            name='sala_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revisar.saladocumentoapp'),
        ),
    ]
