# Generated by Django 3.2.6 on 2021-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar', '0003_auto_20211124_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='saladocumentoapp',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
