# Generated by Django 3.2.6 on 2021-11-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar', '0004_saladocumentoapp_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarevisarapp',
            name='archivo_corregir',
            field=models.FileField(null=True, upload_to='material_estudiante_perfil/'),
        ),
    ]
