# Generated by Django 3.2.6 on 2021-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar', '0005_alter_salarevisarapp_archivo_corregir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saladocumentoapp',
            name='tipo',
            field=models.CharField(choices=[('perfil', 'Perfil'), ('proyecto', 'Proyecto'), ('tribunal', 'Proyecto Tribunal')], max_length=50, null=True),
        ),
    ]
