# Generated by Django 4.0.2 on 2022-03-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar', '0008_salarevisarapp_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarevisarapp',
            name='archivo_corregir_web',
            field=models.URLField(null=True),
        ),
    ]
