# Generated by Django 4.0.2 on 2022-03-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar', '0009_salarevisarapp_archivo_corregir_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='saladocumentoapp',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
