# Generated by Django 4.0.2 on 2022-04-19 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revisar', '0010_saladocumentoapp_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSalaRevisarApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revisar.salarevisarapp')),
            ],
        ),
    ]
