# Generated by Django 4.0.2 on 2022-04-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revisar', '0011_notasalarevisarapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasalarevisarapp',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revisar.salarevisarapp'),
        ),
    ]
