# Generated by Django 4.0.2 on 2022-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisar', '0012_alter_notasalarevisarapp_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasalarevisarapp',
            name='nota_max',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='notasalarevisarapp',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
